aircnc/src/main/java/com/gurudev/aircnc/constant/Regex.java
aircnc/src/main/java/com/gurudev/aircnc/domain/base/BaseIdEntity.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/Email.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/Member.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/Password.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/PhoneNumber.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/Role.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/Address.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/Room.java
aircnc/src/test/java/com/gurudev/aircnc/domain/member/entity/EmailTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/member/entity/MemberTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/member/entity/PasswordTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/member/entity/PhoneNumberTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/AddressTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/RoomTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/util/Fixture.java

room 엔티티를 개발하였습니다.
길이 제한의 검증에 대한 방식,
값객체의 동일성 테스트 방식에 대한 조율이 필요할 것 같습니다.
추가로 Fixture에 테스트시 필요한 인스턴스를 몰아 넣을 수 있도록 하였습니다.

[AIR-41] 숙소 도메인 개발

---

aircnc/src/main/java/com/gurudev/aircnc/constant/Regex.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/entity/Trip.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/entity/TripStatus.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/repository/TripRepository.java
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/entity/TripTest.java

- Trip, TripStatus 구현 및 테스트
- TripRepository

[AIR-86] Trip 도메인 및 리포지토리 작성

---

aircnc/src/main/java/com/gurudev/aircnc/domain/room/entity/Address.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/entity/Room.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/entity/RoomPhoto.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/entity/RoomPhotos.java

[AIR-47] 숙소 도메인 코드 주석 추가

---

aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/Email.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/Member.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/Password.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/PhoneNumber.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/Role.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/repository/MemberRepository.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/service/MemberService.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/service/MemberServiceImpl.java
aircnc/src/main/java/com/gurudev/aircnc/exception/NoSuchMemberException.java
aircnc/src/test/java/com/gurudev/aircnc/domain/member/service/MemberServiceTest.java

[AIR-26] 회원 등록 서비스 구현

---

aircnc/src/main/java/com/gurudev/aircnc/domain/trip/entity/Trip.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripService.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripServiceImpl.java
aircnc/src/main/java/com/gurudev/aircnc/exception/TripReservationException.java
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/entity/TripTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/service/TripServiceImplTest.java

[AIR-87] 여행 등록 서비스 구현

---

aircnc/src/main/java/com/gurudev/aircnc/exception/NoSuchRoomException.java

feat: NoSuchRoomException 추가 [AIR-87]

---

aircnc/src/main/java/com/gurudev/aircnc/configuration/SecurityConfig.java
aircnc/src/main/java/com/gurudev/aircnc/constant/Regex.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/Member.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/Password.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/service/MemberServiceImpl.java
aircnc/src/test/java/com/gurudev/aircnc/domain/member/entity/PasswordTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/member/service/MemberServiceTest.java

[AIR-22] 회원 로그인 기능 서비스 테스트 수정

---

README.md
aircnc/src/main/resources/banner.txt

- README 작성, banner.txt
README 는 현지님이 노션에 올리신걸 사용하였습니다.
banner 는 가장 귀여운 것으로 하였습니다.

[AIR-106] README 작성, banner.txt 추가

---

aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/RoomService.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/RoomServiceImpl.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/entity/RoomTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/service/RoomServiceImplTest.java

[AIR-51] 숙소 전체 조회

---

aircnc/src/main/java/com/gurudev/aircnc/domain/trip/repository/TripRepository.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripService.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripServiceImpl.java
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/service/TripServiceImplTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/util/Fixture.java

[AIR-90] 숙소 조회 서비스 개발

---

aircnc/src/main/java/com/gurudev/aircnc/domain/trip/repository/TripRepository.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripService.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripServiceImpl.java
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/service/TripServiceImplTest.java

[AIR-93] 여행 상세 조회 서비스

---

aircnc/src/main/java/com/gurudev/aircnc/domain/room/entity/Room.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/entity/RoomTest.java

- 숙소 변경 도메인 로직 개발 및 테스트
- 숙소 변경 API 에서 roomId가 필요해서 API Docs에 roomId 추가하였습니다
- 기존 숙소 변경 API `/hosts/{hostId}/rooms`
- 변경 숙소 변경 API `/hosts/{hostId}/rooms/{roomId}`

[AIR-56] 숙소 변경 도메인 로직 개발

---

aircnc/src/main/java/com/gurudev/aircnc/controller/RoomController.java
aircnc/src/main/java/com/gurudev/aircnc/controller/dto/MemberDto.java
aircnc/src/main/java/com/gurudev/aircnc/controller/dto/RoomDto.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/entity/Address.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/entity/Room.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/RoomService.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/RoomServiceImpl.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/entity/Trip.java
aircnc/src/main/resources/application.yaml
aircnc/src/test/java/com/gurudev/aircnc/controller/RoomControllerTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/entity/RoomTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/service/LocalRoomPhotoServiceTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/service/RoomServiceImplTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/service/TripServiceImplTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/util/Fixture.java

- 숙소 등록 API (`RoomController.register`)
- 숙소 생성 방식 변경 (생성자에서 `host` 전달 받지 않고 서비스에서 `revision`을 적용함)
- 이것 저것 리팩토링
- 그러고보니 form 데이터를 입력받는 숙소 등록의 경우 Nested 를 할 필요가 없네요... 제거하는것이 좋을 것 같습니다.

[AIR-49] 숙소 등록 API

---

aircnc/src/main/java/com/gurudev/aircnc/domain/room/entity/Room.java
aircnc/src/main/java/com/gurudev/aircnc/exception/Preconditions.java
aircnc/src/main/resources/db.migration/schema.sql
aircnc/src/test/java/com/gurudev/aircnc/controller/MemberControllerTest.java
aircnc/src/test/resources/application.yml

[AIR-120] fix:   @JoinColumn 추가 

---

aircnc/src/main/java/com/gurudev/aircnc/configuration/jwt/JwtAuthentication.java
aircnc/src/main/java/com/gurudev/aircnc/controller/RoomController.java
aircnc/src/main/java/com/gurudev/aircnc/controller/dto/RoomDto.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/Email.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/Member.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/PhoneNumber.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/dto/RoomDto.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/dto/RoomPhotoDto.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/entity/Room.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/entity/RoomPhoto.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/RoomService.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/RoomServiceImpl.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/entity/Trip.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/service/RoomServiceImplTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/service/TripServiceImplTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/util/Dto.java

[AIR-121] 숙소 등록 서비스 리팩토링

---

aircnc/src/main/java/com/gurudev/aircnc/configuration/JwtConfig.java
aircnc/src/main/java/com/gurudev/aircnc/configuration/PasswordEncoderConfig.java
aircnc/src/main/java/com/gurudev/aircnc/configuration/SecurityConfig.java
aircnc/src/main/java/com/gurudev/aircnc/configuration/jwt/Jwt.java
aircnc/src/main/java/com/gurudev/aircnc/configuration/jwt/JwtAuthentication.java
aircnc/src/main/java/com/gurudev/aircnc/configuration/jwt/JwtAuthenticationFilter.java
aircnc/src/main/java/com/gurudev/aircnc/configuration/jwt/JwtAuthenticationProvider.java
aircnc/src/main/java/com/gurudev/aircnc/configuration/jwt/JwtAuthenticationToken.java
aircnc/src/main/java/com/gurudev/aircnc/configuration/jwt/JwtProperties.java
aircnc/src/main/resources/application.yaml
aircnc/src/test/resources/application.yml

- configuration 패키지 리팩토링
- jwt 관련 설정 `JwtConfig` 로 분리
- `SecurityConfig` 에서 `ApplicationContext` 제거
-  순환 의존성 해결
-  `PasswordEncoderConfig` 에서 `PasswordEncoder` 등록

[AIR-120] configuration 패키지 리팩토링

---

aircnc/src/main/java/com/gurudev/aircnc/AircncApplication.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/Password.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/repository/TripRepository.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripService.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripServiceImpl.java
aircnc/src/main/java/com/gurudev/aircnc/exception/Preconditions.java
aircnc/src/main/java/com/gurudev/aircnc/infrastructure/scheduler/TripStatusScheduler.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/service/RoomServiceImplTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/entity/TripTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/service/TripServiceImplTest.java
aircnc/src/test/java/com/gurudev/aircnc/infrastructure/scheduler/SchedulerTest.java
aircnc/src/test/java/com/gurudev/aircnc/infrastructure/scheduler/TripStatusSchedulerTest.java

- 체크인 벌크성 수정쿼리 및 스케쥴러 구현 및 테스트

[AIR 130] 체크인 벌크성 수정쿼리 및 스케쥴러 구현 및 테스트

---

aircnc/src/main/java/com/gurudev/aircnc/domain/trip/repository/TripRepository.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripService.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripServiceImpl.java
aircnc/src/main/java/com/gurudev/aircnc/infrastructure/scheduler/TripStatusScheduler.java
aircnc/src/test/java/com/gurudev/aircnc/infrastructure/scheduler/TripStatusSchedulerTest.java

바로 전 RESERVED -> TRAVELLING 스케쥴러 개발과 내용이 같습니다.
확인하고 바로 merge해 주셔도 좋을것 같아요!

[AIR-131] TRAVELLING -> DONE 스케쥴러 개발

---

aircnc/src/main/java/com/gurudev/aircnc/controller/RoomController.java
aircnc/src/main/java/com/gurudev/aircnc/controller/dto/RoomDto.java
aircnc/src/test/java/com/gurudev/aircnc/controller/RoomControllerTest.java
aircnc/src/test/java/com/gurudev/aircnc/controller/support/BaseControllerTest.java

[AIR-58] 숙소 변경 API

---

aircnc/src/main/java/com/gurudev/aircnc/controller/TripController.java
aircnc/src/main/java/com/gurudev/aircnc/controller/dto/TripDto.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/repository/TripRepository.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripService.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripServiceImpl.java
aircnc/src/test/java/com/gurudev/aircnc/controller/TripControllerTest.java
aircnc/src/test/java/com/gurudev/aircnc/controller/support/BaseControllerTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/service/TripServiceImplTest.java

- 여행 목록 조회, 상세 조회, 취소 API
- 서브 테스크가 너무 세분화 된거 같아 빠른 작업을 위해 한 PR 에 진행하였습니다.

[AIR-91] 여행 목록 조회, 상세 조회, 취소 API

---

aircnc/src/main/java/com/gurudev/aircnc/controller/RoomController.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/entity/Trip.java
aircnc/src/test/java/com/gurudev/aircnc/controller/RoomControllerTest.java

- 숙소 삭제 API
- TripStatus에 @Enumerated(STRING) 추가 (발견해서 하나 슬쩍 묻었습니다..)

[AIR-61] 숙소 삭제 API

---

aircnc/src/main/java/com/gurudev/aircnc/controller/ApiResponse.java
aircnc/src/main/java/com/gurudev/aircnc/controller/CustomControllerAdvice.java
aircnc/src/main/java/com/gurudev/aircnc/controller/MemberController.java
aircnc/src/main/java/com/gurudev/aircnc/controller/RoomController.java
aircnc/src/main/java/com/gurudev/aircnc/controller/TripController.java
aircnc/src/main/java/com/gurudev/aircnc/controller/dto/RoomDto.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/Password.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/service/MemberServiceImpl.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/command/RoomCommand.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripService.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripServiceForScheduler.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripServiceForSchedulerImpl.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripServiceImpl.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/command/TripCommand.java
aircnc/src/main/java/com/gurudev/aircnc/infrastructure/aws/s3/S3Properties.java
aircnc/src/main/java/com/gurudev/aircnc/infrastructure/mail/MailSender.java
aircnc/src/main/java/com/gurudev/aircnc/infrastructure/scheduler/TripStatusScheduler.java
aircnc/src/main/java/com/gurudev/aircnc/infrastructure/security/jwt/JwtProperties.java
aircnc/src/main/resources/application.yaml
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/service/BaseTripServiceTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/service/TripServiceForSchedulerImplTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/service/TripServiceImplTest.java
aircnc/src/test/resources/application.yml

- 이것 저것 리팩토링 했습니다.
- `ApiResponse` 라는 `ResponseEntity` 생성용 팩터리 클래스 추가
- 컨트롤러에 endpoint 별 주석 추가
- `TripService` 에서 bulk 담당하는 부분 분리
- 테스트도 분리하는 과정에서 `BaseTripServiceTest` 추가
-  `@ConfigurationProperties`의 `prefix` 를 `infrastructure` 패키지 구조 와 통일시킴 -> `application yml` 파일 수정

[AIR-134] 이것 저것 리팩토링

---

aircnc/src/main/java/com/gurudev/aircnc/domain/room/repository/RoomRepository.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/RoomService.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/RoomServiceImpl.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/service/RoomServiceImplTest.java

[AIR-54] 숙소 상세 조회 서비스

---

aircnc/src/main/java/com/gurudev/aircnc/controller/EmailController.java
aircnc/src/main/java/com/gurudev/aircnc/controller/RoomController.java
aircnc/src/main/java/com/gurudev/aircnc/controller/TripController.java
aircnc/src/main/java/com/gurudev/aircnc/infrastructure/mail/entity/MailType.java
aircnc/src/main/java/com/gurudev/aircnc/infrastructure/mail/service/AbstractEmailService.java
aircnc/src/main/java/com/gurudev/aircnc/infrastructure/mail/service/EmailService.java
aircnc/src/main/java/com/gurudev/aircnc/infrastructure/mail/service/MemberEmailService.java
aircnc/src/main/java/com/gurudev/aircnc/infrastructure/mail/service/RoomEmailService.java
aircnc/src/main/java/com/gurudev/aircnc/infrastructure/mail/service/TripEmailService.java
aircnc/src/test/java/com/gurudev/aircnc/infrastructure/mail/EmailServiceTest.java

fix: test recover

---

aircnc/docs/asciidoc/api/Room-API.adoc
aircnc/src/main/java/com/gurudev/aircnc/controller/RoomController.java
aircnc/src/main/java/com/gurudev/aircnc/controller/dto/RoomDto.java
aircnc/src/test/java/com/gurudev/aircnc/controller/RoomControllerTest.java

- 호스트 자신 숙소 조회 API 개발
-  RoomDto에서도 Trip처럼 Response를 분리하였습니다.

[AIR-85] 호스트 자신 숙소 조회 API 개발

---

aircnc/docs/asciidoc/api/HostRoom-API.adoc
aircnc/docs/asciidoc/api/Room-API.adoc
aircnc/docs/asciidoc/index.adoc
aircnc/src/main/java/com/gurudev/aircnc/configuration/SecurityConfig.java
aircnc/src/main/java/com/gurudev/aircnc/controller/HostRoomController.java
aircnc/src/main/java/com/gurudev/aircnc/controller/RoomController.java
aircnc/src/test/java/com/gurudev/aircnc/controller/HostRoomControllerTest.java
aircnc/src/test/java/com/gurudev/aircnc/controller/RoomControllerTest.java
aircnc/src/test/java/com/gurudev/aircnc/controller/support/BaseControllerTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/service/RoomPhotoServiceImplTest.java

- 기존의 RoomController -> HostRoomController로 이름 변경(test클래스도 RoomControllerTest -> HostRoomControllerTest)
- RoomController 생성 (endpoint : api/v1/rooms)
- 테스트 구현
- RestDocs 변경
- 기존 Room-API.adoc -> HostRoom-API.adoc)
- Room-API.adoc 추가
-

[AIR-52] 숙소 리스트 조회 기능

---

aircnc/src/main/java/com/gurudev/aircnc/domain/room/entity/Room.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/repository/RoomRepository.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/RoomServiceImpl.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/command/RoomCommand.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/entity/RoomTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/service/RoomServiceImplTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/service/command/RoomCommandTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/util/Fixture.java

[AIR-142] 숙소 유효성 검사 커맨드로 이동 

---

aircnc/src/main/java/com/gurudev/aircnc/domain/room/entity/Room.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/RoomServiceImpl.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/command/RoomCommand.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/entity/RoomTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/util/Fixture.java

[AIR-142] 엔티티에서 컬렉션 초기화 방식 변경 

---

aircnc/docs/asciidoc/api/Room-API.adoc
aircnc/src/main/java/com/gurudev/aircnc/configuration/SecurityConfig.java
aircnc/src/main/java/com/gurudev/aircnc/controller/RoomController.java
aircnc/src/main/java/com/gurudev/aircnc/controller/dto/RoomDto.java
aircnc/src/test/java/com/gurudev/aircnc/controller/RoomControllerTest.java
aircnc/src/test/java/com/gurudev/aircnc/controller/TripControllerTest.java
aircnc/src/test/java/com/gurudev/aircnc/controller/support/BaseControllerTest.java

-  비회원/회원이 숙소를 상세 조회
-  RoomController 숙소 상세 테스트 및 기능 구현
- jsonPath("$.room.unAvailableDays",hasSize(4)) 부분에서 각각의 값을 1:1 비교하고자 하는데 조언을 얻고자 합니다
-  restdocs 작성 부분에서 pathParameters(parameterWithName("roomId").description("숙소 아이디")) 한번 봐주시면 감사하겠습니다

[AIR-55] 숙소 상세 조회 api 구현

---

aircnc/src/main/java/com/gurudev/aircnc/configuration/SecurityConfig.java
aircnc/src/main/java/com/gurudev/aircnc/controller/CustomControllerAdvice.java
aircnc/src/main/java/com/gurudev/aircnc/controller/EmailAuthController.java
aircnc/src/main/java/com/gurudev/aircnc/controller/HostRoomController.java
aircnc/src/main/java/com/gurudev/aircnc/controller/MemberController.java
aircnc/src/main/java/com/gurudev/aircnc/domain/common/AttachedFile.java
aircnc/src/main/java/com/gurudev/aircnc/domain/common/BaseIdEntity.java
aircnc/src/main/java/com/gurudev/aircnc/domain/member/entity/Member.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/entity/Room.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/entity/RoomPhoto.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/RoomPhotoService.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/RoomPhotoServiceImpl.java
aircnc/src/main/java/com/gurudev/aircnc/domain/room/service/RoomServiceImpl.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/entity/Trip.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripServiceForSchedulerImpl.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/TripServiceImpl.java
aircnc/src/main/java/com/gurudev/aircnc/domain/trip/service/command/TripCommand.java
aircnc/src/main/java/com/gurudev/aircnc/infrastructure/event/TripEvent.java
aircnc/src/main/java/com/gurudev/aircnc/infrastructure/event/TripEventRunner.java
aircnc/src/main/java/com/gurudev/aircnc/infrastructure/mail/utils/MapUtils.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/service/RoomPhotoServiceImplTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/room/service/RoomServiceImplTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/service/BaseTripServiceTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/service/TripServiceForSchedulerImplTest.java
aircnc/src/test/java/com/gurudev/aircnc/domain/trip/service/TripServiceImplTest.java
aircnc/src/test/java/com/gurudev/aircnc/infrastructure/mail/EmailServiceTest.java

- base 라는 패키지 이름을 common 으로 바꾸었습니다.
- mapUtil 의 위치를 domain.util 에서 infrastructure.email.util 로 바꾸었습니다.
- 제 생각에 적절한 메시지에 따라 구분이 되지 않은 것 같은 예외를 바꾸었습니다.
- 여행 추가에 검증 로직이 추가 되었는데 그에 따른 테스트 오류를 수정하였습니다

 [AIR-144] 예외 처리 리팩토링
